name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build code
        run: |
          echo "Compiling the code..."
          echo "Compile complete."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          echo "Running unit tests... This will take about 60 seconds."
          sleep 60
          echo "Code coverage is 90%"
      - name: Run lint tests
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 10
          echo "No lint issues found."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production
        if: github.ref == 'refs/heads/main' # Only deploy on main branch
        run: |
          echo "Deploying application..."
          echo "Application successfully deployed."
