name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile code
      run: echo "Compiling the code..."
    - name: Run unit tests
      run: |
        echo "Running unit tests... This will take about 60 seconds."
        sleep 60
        echo "Code coverage is 90%"
    - name: Lint code
      run: |
        echo "Linting code... This will take about 10 seconds."
        sleep 10
        echo "No lint issues found."
    - name: Deploy application
      if: success()
      run: echo "Deploying application..."
