name: PHP Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        run: brew install php

      - name: Build
        run: php -f index.php

  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHPUnit
        run: brew install phpunit

      - name: Run tests
        run: phpunit tests/

  deploy:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: ssh user@example.com "cd /path/to/project && git pull origin main && php -f index.php"
